version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'fundoo'
       MYSQL_USER: 'myprojectuser'
       MYSQL_PASSWORD: 'Admin@123'
       MYSQL_ROOT_PASSWORD: 'Admin@123'

  web:
#    image: 7204776016/fundoo-images:djangoimage
    build: .
    command:  bash -c " python manage.py migrate && python manage.py loaddata db.json && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: .
      dockerfile: Dockerfilenginxx
    depends_on:
      - web
    ports:
      - "80:80"

  redis:
    image: redis
    ports:
      - "6379:6379"
