#!/bin/bash

#cd home/admin1/PycharmProjects/fundoo
#source venv/bin/activate
#pytest



NAME="fundoo"                                 # Name of the application
DJANGODIR=home/admin1/PycharmProjects/fundoo          # Django project directory
SOCKFILE=localhost:8000 # we will communicte using this unix socket
USER=admin1                                       # the user to run as
GROUP=admin1                                    # the group to run as
NUM_WORKERS=3                                    # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=fundoo.settings            # which settings file should Django use
DJANGO_WSGI_MODULE=fundoo.wsgi                    # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd home/admin1/PycharmProjects/fundoo
Source venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /home/admin1/PycharmProjects/fundoo/venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
 --name $NAME \
 --workers $NUM_WORKERS \
 --user=$USER --group=$GROUP \
 --bind=$SOCKFILE \
 --log-level=debug \
 --log-file=-
