# Generated by Django 2.2.5 on 2019-09-30 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='label_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('note', models.CharField(max_length=500)),
                ('image', models.ImageField(default=None, max_length=500, upload_to='')),
                ('archive', models.BooleanField(default=False, verbose_name='is_archived')),
                ('delete_note', models.BooleanField(default=False, verbose_name='delete_note')),
                ('copy', models.BooleanField(default=False, verbose_name='make a copy')),
                ('checkbox', models.BooleanField(default=False, verbose_name='check box')),
                ('pin', models.BooleanField(default=False)),
                ('colaborator', models.ManyToManyField(related_name='collaborator', to=settings.AUTH_USER_MODEL)),
                ('label', models.ManyToManyField(to='note.Lable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
