# Generated by Django 2.2.5 on 2019-09-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Notes')),
            ],
        ),
    ]
