# Generated by Django 2.2.6 on 2019-11-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Query',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Search Query'),
        ),
    ]
