# Generated by Django 2.2.6 on 2019-10-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(default='', editable=False, max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='notes',
            name='label',
        ),
        migrations.AddField(
            model_name='notes',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label', to='note.Label'),
        ),
    ]
