# Generated by Django 2.2.5 on 2019-09-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_lable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lable',
            name='label',
        ),
    ]
