# Generated by Django 2.2.6 on 2019-11-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_notes_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Query',
            new_name='query',
        ),
    ]
