# Generated by Django 2.2.6 on 2019-11-11 10:59

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_notes_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, colors=['#FF0000', '#00FF00', '#0000FF'], null=True),
        ),
    ]
