# Generated by Django 2.2.5 on 2019-10-01 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0002_auto_20190930_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Colabrator_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='colaborator',
            field=models.ManyToManyField(blank=True, related_name='collaborator', to='note.collaborator'),
        ),
    ]
