# Generated by Django 2.2.6 on 2019-10-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20191012_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='label',
        ),
    ]
