# Generated by Django 2.2.5 on 2019-09-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_remove_lable_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='trash',
        ),
    ]
