# Generated by Django 2.2.6 on 2019-10-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_notes_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='share',
        ),
    ]
