# Generated by Django 2.2.5 on 2019-10-01 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20191001_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='colaborator',
            field=models.ManyToManyField(blank=True, related_name='collaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='collaborator',
        ),
    ]
