# Generated by Django 2.2.6 on 2019-11-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'user detail', 'verbose_name_plural': 'user details'},
        ),
    ]
