# Generated by Django 2.2.6 on 2019-11-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallogin',
            options={'verbose_name': 'social login user', 'verbose_name_plural': 'social login users'},
        ),
        migrations.AlterField(
            model_name='sociallogin',
            name='EXTRA_PARAMS',
            field=models.TextField(max_length=1000, verbose_name='Extra Params'),
        ),
        migrations.AlterField(
            model_name='sociallogin',
            name='full_name',
            field=models.CharField(max_length=500, verbose_name='Full name '),
        ),
        migrations.AlterField(
            model_name='sociallogin',
            name='provider',
            field=models.CharField(max_length=500, verbose_name='Service Provider'),
        ),
        migrations.AlterField(
            model_name='sociallogin',
            name='unique_id',
            field=models.CharField(max_length=500, verbose_name='Unique Id'),
        ),
        migrations.AlterField(
            model_name='sociallogin',
            name='username',
            field=models.CharField(max_length=500, verbose_name='Username'),
        ),
    ]
